### ISSUE TITLE
saspy gets fnctl error is pandas is not installed

### ISSUE THREAD

**Issue by tomweber-sas** [sassoftware/saspy#10]
This issue showed up in sas_kernel (Jupyter and SAS Grid #27). Posting here for tracking.

>> import saspy
>>> sas = saspy.SASsession(cfgname='iomlinux')
Please enter the IOM user id: pruddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/<usr>/anaconda3/envs/saspy/lib/python3.6/site-packages/saspy/sasbase.py", line 236, in __init__
    self._io = sasioiom.SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "/home/<usr>/anaconda3/envs/saspy/lib/python3.6/site-packages/saspy/sasioiom.py", line 161, in __init__
    self._startsas()
  File "/home/<usr>/anaconda3/envs/saspy/lib/python3.6/site-packages/saspy/sasioiom.py", line 310, in _startsas
    fcntl.fcntl(self.stdout, fcntl.F_SETFL, os.O_NONBLOCK)
NameError: name 'fcntl' is not defined

**Comment by tomweber-sas** [comment]
The problem was that I had multiple includes in a single try:except: such that it one failed, none of them were included. This is fixed and verified at master with 65bcbf2e0e97accae3d416e6d5d72c27c5309096.
