### ISSUE TITLE
Add option to trim data values when converting SAS Data set to pandas DataFrame

### ISSUE THREAD

**Issue by siegerts** [sassoftware/saspy#111]
It seems that character values are right padded when converting from the fixed width SAS data set to the variable with DataFrame.  This additional buffer introduces a loss of data integrity because of the unexpected structure.

A simple example for conversion is:

```python
sd = sas.sasdata("test")
df = sd.to_df() // or sas.sd2df()
```
Currently, a possible workaround is by stripping the data after the conversion:

```python 
df_trimmed = df.applymap(lambda x: x.strip() if type(x) is str else x)
```

Maybe, adjusting the API to allow an additional parameter flag that will execute trimming.  Something like _**trim=True**_:

```python
sas.sd2df(dataset, trim=True)
```

Thanks! 🍻

**Comment by jld23** [comment]
@siegerts, can you  either provide the contents of `test` or use a dataset from the SASHELP library so that we can ensure we're seeing the issue?

**Comment by tomweber-sas** [comment]
Ah, I actually know of this one. Talked with him last week about this. I know what needs to be done.
It is just trailing blanks in char variables since SAS has fixed width columns. No need to bloat dataframes with that.

Thanks,
Tom

**Comment by siegerts** [comment]
_Function to test_
```python
import saspy
from pandas.io.json import json_normalize

# initialize our session
sas = saspy.SASsession()


def remove_duplicates(data, name, sort_variable):
    """
    Sort and deduplicate normalized data
    using PROC SORT.
    """

    dataframe = json_normalize(data)

    sas.df2sd(dataframe, table=name)

    sas.submit(
        f"""
        proc sort data={name} NODUPKEY;
            by DESCENDING '{sort_variable}'n;
        run;
        quit;
        """
    )   
    
    return sas.sasdata(f"{name}")
```

_Tests_

```python

import unittest
from pandas.io.json import json_normalize
from pandas.util.testing import assert_frame_equal


class TestDataProcess(unittest.TestCase):

    def setUp(self):
        self.data = [
            {
                "id": 1,
                "name": "Leanne Graham",
                "username": "Bret",
                "email": "Sincere@april.biz",
                "address": {
                    "street": "Kulas Light",
                    "suite": "Apt. 556",
                    "city": "Gwenborough",
                    "zipcode": "92998-3874",
                    "geo": {
                        "lat": "-37.3159",
                        "lng": "81.1496"
                    }
                },
                "phone": "1-770-736-8031 x56442",
                "website": "hildegard.org",
                "company": {
                    "name": "Romaguera-Crona",
                    "catchPhrase": "Multi-layered client-server neural-net",
                    "text": "harness real-time e-markets"
                }
            },
            {
                "id": 2,
                "name": "Ervin Howell",
                "username": "Antonette",
                "email": "Shanna@melissa.tv",
                "address": {
                    "street": "Victor Plains",
                    "suite": "Suite 879",
                    "city": "Wisokyburgh",
                    "zipcode": "90566-7771",
                    "geo": {
                        "lat": "-43.9509",
                        "lng": "-34.4618"
                    }
                },
                "phone": "010-692-6593 x09125",
                "website": "anastasia.net",
                "company": {
                    "name": "Deckow-Crist",
                    "catchPhrase": "Proactive didactic contingency",
                    "text": "synergize scalable supply-chains"
                }
            }
        ]

  
    # compare actuals
    def test_remove_duplicate_data_actual(self):
        """
        Remove duplicate data from an input dataset
        as defined by a `by variable` parameter.
        """
        data_with_duplicates = self.data + self.data

        actual = remove_duplicates(data_with_duplicates, 'users', 'name').to_df()
        
        # convert both data objects to pandas dataframes
        expected = json_normalize(self.data)
        
        # trim any right space from SAS fixed width
        actual_trimmed = actual.applymap(lambda x: x.strip() if type(x) is str else x)
       
        # compare actuals 
        assert_frame_equal(expected, actual)
       
    
    # compare trimmed
    def test_remove_duplicate_data_trimmed(self):
        """
        Remove duplicate data from an input dataset
        as defined by a `by variable` parameter.
        """
        data_with_duplicates = self.data + self.data

        actual = remove_duplicates(data_with_duplicates, 'users', 'name').to_df()
        
        # convert both data objects to pandas dataframes
        expected = json_normalize(self.data)
        
        # trim any right space from SAS fixed width
        actual_trimmed = actual.applymap(lambda x: x.strip() if type(x) is str else x)
       
        # compare trimmed
        assert_frame_equal(expected, actual_trimmed)
   

    def tearDown(self):
        pass
```

_Results_ - trimmed test passes but the actuals test does not.

```bash
F.
======================================================================
FAIL: test_remove_duplicate_data_actual (__main__.TestDataProcess)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<ipython-input-4-1095f9c8dac9>", line 76, in test_remove_duplicate_data_actual
    assert_frame_equal(expected, actual)
  File "/opt/sasinside/anaconda3/lib/python3.6/site-packages/pandas/util/testing.py", line 1386, in assert_frame_equal
    obj='DataFrame.iloc[:, {0}]'.format(i))
  File "/opt/sasinside/anaconda3/lib/python3.6/site-packages/pandas/util/testing.py", line 1265, in assert_series_equal
    obj='{0}'.format(obj))
  File "pandas/_libs/testing.pyx", line 59, in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:4156)
  File "pandas/_libs/testing.pyx", line 173, in pandas._libs.testing.assert_almost_equal (pandas/_libs/testing.c:3274)
  File "/opt/sasinside/anaconda3/lib/python3.6/site-packages/pandas/util/testing.py", line 1092, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: DataFrame.iloc[:, 0] are different

DataFrame.iloc[:, 0] values are different (100.0 %)
[left]:  [Gwenborough, Wisokyburgh]
[right]: [Gwenborough , Wisokyburgh ]

----------------------------------------------------------------------
Ran 2 tests in 2.382s

FAILED (failures=1)
```

**Comment by tomweber-sas** [comment]
Curiously, I'm not seeing any trailing blanks in the dataframe columns after importing it from SAS.
What version of saspy are you running? You can just submit you SASsession object (sas).
There were a number of changes and fixed to this code a couple versions ago. Might already be fixed.

**Comment by siegerts** [comment]
Okay, I was using an older version.  I've updated to `2.2.1` but have encountered another issue - the data for the last column is lost when using `df2sd`.

**Comment by tomweber-sas** [comment]
are you sure? I used the json you have above and creating the dataframe from that looks identical to the SAS data set and the round tripped data frame. But I see that the columns are in a different order than your json; the original data frame is in a different order. I see the company.* columns in the middle, not after website. the json-normalize to DF seemed to put them in a different order.

**Comment by tomweber-sas** [comment]
ok, I see it was that you were missing the data values for website. all the columns were there, but the data was missing for that one. Looks like it'snot making it to SAS on the dataframe2dasdata, so it's not there to be shown when you look at it or bring it back to a data frame.
I'll track that down. It appears specific to the STDIO access method. It's clean over IOM.
Tom

**Comment by tomweber-sas** [comment]
Wow, that's a terrible bug on my part. Coded right in the IOM access method but got it wrong in STDIO.
It is dropping the data for the last column. I've fix this and pushed it to master.

I believe this will them make your code all work cleanly now.
Let me know,
Tom
