### ISSUE TITLE
Tabulate enhancement imposes python 3.5 or higher due to syntax error

### ISSUE THREAD

**Issue by tomweber-sas** [sassoftware/saspy#145]
The new Tabulate support has some syntax that fails in pre 3.5 python versions. This broke our interal work due to it using 3.4. I've had to remove this in the 2.2.6 release we we can build and run with the rest of what's in saspy 2.2.5. 
Once I figure out what the issue is and fix it so it's compatible with earlier py3 versions, it will be added back.

```
SyntaxError: invalid syntax
[I 13:40:40.207 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.4/site-packages/sas_kernel/__main__.py", line 18, in <module>
    from .kernel import SASKernel
  File "/usr/lib/python3.4/site-packages/sas_kernel/kernel.py", line 27, in <module>
    from saspy.SASLogLexer import SASLogStyle, SASLogLexer
  File "/usr/lib/python3.4/site-packages/saspy/__init__.py", line 16, in <module>
    from saspy.sasbase        import *
  File "/usr/lib/python3.4/site-packages/saspy/sasbase.py", line 72, in <module>
    from saspy.sastabulate import Tabulate
  File "/usr/lib/python3.4/site-packages/saspy/sastabulate.py", line 199
    return [Statistic(args[i], **label_kwargs[i], **format_kwargs[i]) for i in range(len(args))]
```

I tried 'unrolling' the offending syntax, but that wasn't the issue. I'll have to install 3.4 to figure out what it's really complaining about.
```
>>> import saspy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/saspy/__init__.py", line 16, in <module>
    from saspy.sasbase        import *
  File "/usr/lib/python3.4/site-packages/saspy/sasbase.py", line 72, in <module>
    from saspy.sastabulate import Tabulate
  File "/usr/lib/python3.4/site-packages/saspy/sastabulate.py", line
211
    ret.append(Statistic(args[i], **label_kwargs[i], **format_kwargs[i]))
                                                   ^
SyntaxError: invalid syntax
```
@jasonphillips  do you know how to fix this syntax so it works correctly with earlier py3 versions?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey Jason, thanks! Sorry, I've been heads down all week. And I'm heading out in the morning, but I'll get this in either in the morning if I can or after the 4th. The emergency was dealt with just commenting this out for what we needed internally - last minute thing of course :). I'll get it back in and build a new pypi as soon as I can. Don't worry, this wasn't your problem, but mine for not validating it more thoroughly. Yes, trying to automate publicly when it needs a proprietary connection is non-standard, to say the least. I don't have that many contributions though, so I should do better w/ backward compatibility when I test out a PR. 
This one's on me! You're good!
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Thanks again Jason! Closing this as it was merged in.
Tom
