### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by hjsdssz** [sassoftware/saspy#165]
Hi, 

I am trying to install saspy-2.2.7 version from Ipython (Jupyter), but it gives me the error below.
Can someone help? 
Many thx!

  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F2350>, 'Connection to github.com timed out. (connect timeout=15)')': /sassoftware/saspy/releases/saspy-2.2.7.tar.gz
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F2750>, 'Connection to github.com timed out. (connect timeout=15)')': /sassoftware/saspy/releases/saspy-2.2.7.tar.gz
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F2770>, 'Connection to github.com timed out. (connect timeout=15)')': /sassoftware/saspy/releases/saspy-2.2.7.tar.gz
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F28D0>, 'Connection to github.com timed out. (connect timeout=15)')': /sassoftware/saspy/releases/saspy-2.2.7.tar.gz
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F2970>, 'Connection to github.com timed out. (connect timeout=15)')': /sassoftware/saspy/releases/saspy-2.2.7.tar.gz
Could not install packages due to an EnvironmentError: HTTPConnectionPool(host='github.com', port=80): Max retries exceeded with url: /sassoftware/saspy/releases/saspy-2.2.7.tar.gz (Caused by ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPConnection object at 0x038F2AD0>, 'Connection to github.com timed out. (connect timeout=15)'))

**Comment by tomweber-sas** [comment]
Hey, can you show me what it is you ran? What command from where? 
Thanks!
Tom

**Comment by hjsdssz** [comment]
Hi, Tom:

Thank you for response.
Actually I have already installed saspy and configured the sascfg.py file, now there is a new issue.
Here is the message, I also attached my sascfg.file for your review.
Thanks!

Java Error:
java.lang.UnsupportedClassVersionError: pyiom/saspy2j : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$000(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: pyiom.saspy2j.  Program will exit.
Exception in thread "main" 

Subprocess failed to start. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\python2\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '55106', '-stdoutport', '55107', '-stderrport', '55108', '-zero', '-lrecl', '1048576', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\python2\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 55106 -stdoutport 55107 -stderrport 55108 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
Hey, well the error is:
Could not find the main class: pyiom.saspy2j. Program will exit.
And looking at your classpath, it appears that you have python2?
saspy requires python3, so I suspect that's part of what would be causing this, though it seems a little strange.
Can you confirm what python, and what Java for that matter, you are using?
Thanks!
Tom

**Comment by hjsdssz** [comment]
Hi, Tom:

I am using python3 and java(TM) 6 Update 45.
Thanks!

**Comment by tomweber-sas** [comment]
Do you also have python2 installed? It's easy to have multiple versions and have some commands use one while others are using the other. I'm a little suspicious about this path, and the error about it not being found.
```
C:\python2\Lib\site-packages\saspy\java\saspyiom.jar
```
Can you submit the following to be sure of where you're running?
```
import sys
sys.path
# seperate cell if in a notebook. doesn't matter in line mode
import saspy
saspy 
```
Thanks,
Tom

**Comment by hjsdssz** [comment]
I did install java 8 and uninstall the old java version, now it gives me the error below.

Java Error:
log4j:WARN No appenders could be found for logger (com.sas.services.connection).
log4j:WARN Please initialize the log4j system properly.
com.sas.services.connection.FatalConnectionFactoryException: The application could not find a command to launch a SAS Workspace Server.
	at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:240)
	at com.sas.services.connection.AggregationKernel.doGetConnection(AggregationKernel.java:242)
	at com.sas.services.connection.ConnectionFactoryKernel.getConnection(ConnectionFactoryKernel.java:325)
	at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:69)
	at com.sas.services.connection.ConnectionFactoryShell.getConnection(ConnectionFactoryShell.java:51)
	at pyiom.saspy2j.main(saspy2j.java:187)
Caused by: org.omg.CORBA.NO_IMPLEMENT: The application could not find a command to launch a SAS Workspace Server.  vmcid: 0x0  minor code: 0  completed: No
	at com.sas.iom.orb.brg.Engine.flowLaunchServer(Engine.java:2952)
	at com.sas.iom.orb.brg.Engine.flow(Engine.java:709)
	at com.sas.iom.orb.brg.Engine.initClient(Engine.java:674)
	at com.sas.iom.orb.brg.ORBImpl.uri_to_object(ORBImpl.java:114)
	at com.sas.services.connection.ClusterEnvelope.createObject(ClusterEnvelope.java:293)
	at com.sas.services.connection.ClusterEnvelope.getConnection(ClusterEnvelope.java:78)
	... 5 more

We failed in getConnection
The application could not find a command to launch a SAS Workspace Server.
Subprocess failed to start. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\python2\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '49354', '-stdoutport', '49355', '-stderrport', '49356', '-zero', '-lrecl', '1048576', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94496__prt__xx__sp0__1\deploywiz\sas.core.jar;C:\python2\Lib\site-packages\saspy\java\saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 49354 -stdoutport 49355 -stderrport 49356 -zero -lrecl 1048576  

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
ok, that's good. This problem is documented here: 
https://sassoftware.github.io/saspy/troubleshooting.html#iom

This is due to the windows registry not having a good path to the SAS executable in it. There's a utility to fix is, which will hopefully work. There 's also a workaround if that doesn't work for some reason.

Can you check what's in here:
key=HKEY_CLASSES_ROOTCLSID{440196D4-90F0-11D0-9F41-00A024BB830C}LocalServer32

The fix for this (but see what's there first and then after running the utility) is to run SAS w/ this option:

[C:\...\]sas.exe /regserver

If you look at the last entries in that section of the troubleshooting guide, these are numbers 4 and 5 at the end of that part.

Sorry for these troubles. Hopefully this will be the last thing to get this running. 
Tom

**Comment by hjsdssz** [comment]
No problem Tom. Really appreciate you help here.

key=HKEY_CLASSES_ROOTCLSID{440196D4-90F0-11D0-9F41-00A024BB830C}
under {440196D4-90F0-11D0-9F41-00A024BB830C}, there are four folders: ProgID, TypeLib, Version, VersionIndependentProgID

Sorry, how should I run [C:...]sas.exe /regserver?

**Comment by tomweber-sas** [comment]
Sorry, that just meant run 
```
sas.exe /regserver
```
Though I don't know if the path is found, so fully quality the path to sas.exe if need be, like this
```
C:\Program Files\SASHome\SASFoundation\9.4\sas.exe /regserver
```

**Comment by hjsdssz** [comment]
OK. I see.
But I don't have sas.exe, I downloaded SAS EG through SAS deployment Manager 9.4
The available .exe are sasdm.exe and sasmc.exe

**Comment by hjsdssz** [comment]
Can I run sasdm.exe and use the path for it?

**Comment by tomweber-sas** [comment]
Well, you've configured saspy to run via IOM Local mode. That requires SAS to be installed on you pc. Are you trying to connect to a remote workspace server, like what EG connects to? If so, check out the IOM Remote config:
https://sassoftware.github.io/saspy/install.html#iom

You just need the host name where the object spawner is running and the workspace server port. If there's more than 1 workspace server configured, then the appserver name too for which one.

**Comment by hjsdssz** [comment]
I see.
I just changed to run via remote workspace server.
It gives me the comment, does it mean that I still need to configure my sascfg.py file?

[configure.docx](https://github.com/sassoftware/saspy/files/2333579/configure.docx)


Please enter the IOM user id: x200232
Please enter the password for IOM user : ········
We failed in getConnection
The client has connected to a SAS Metadata Server (v1.0) when it intended to connect to a SAS Workspace Server.

SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SASHome\\SASDeploymentManager\\9.4\\products\\deploywiz__94496__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\python2\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '59506', '-stdoutport', '59507', '-stderrport', '59508', '-iomhost', 'sp20630.corp.ads', '-iomport', '8561', '-user', 'x200232', '-lrecl', '1048576', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.

**Comment by tomweber-sas** [comment]
Nope, but you're getting close :)
Either the hostname was for the metadata server, not the object spawner, or the port was for the metadata server instead of the workspace server. There's a query you can run (from EG or whatever can connect to OMR) to find out those hostnames and ports. It's right here:
https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports

This is the error:
We failed in getConnection
The client has connected to a SAS Metadata Server (v1.0) when it intended to connect to a SAS Workspace Server.

Tom

**Comment by hjsdssz** [comment]
Thank you so much! Tom.
I guess this is a success.

Please enter the IOM user id: x200232
Please enter the password for IOM user : ········
SAS Connection established. Subprocess id is 5016

**Comment by tomweber-sas** [comment]
That looks good. 
You should be able to do stuff now. Here's the quickest to verify:
Whatever your SASsession object it's, I'll assume 'sas'.

cars = sas.sasdata('cars', 'sashelp')
cars.head()

print(sas.saslog())


You should get output and you'll know your good!
Tom

**Comment by tomweber-sas** [comment]
BTW, you can use the _authinfo file to store your credentials so you won't get prompted and won't have to enter them. It's there in the IOM config section that shoes how to set that up.

**Comment by hjsdssz** [comment]
I see. Thanks very much for your help! 
BTW, the code above did give me output.
