### ISSUE TITLE
SAS process has terminated unexpectedly

### ISSUE THREAD

**Issue by rodrigoalatorre** [sassoftware/saspy#463]
We've built an app which, using SASPy connects to a SAS workspace server and retrieves information from two Oracle DB tables. Most of the time, we have no issued with SASPy, but sometimes, specially when the server seems to be under heavy load, SASPy throws an error, which, upon inspecting the logs reads:
"We failed in getConnection
No logical assign for filename _TOMODS1

SAS process has temrminated unexpectedly. Pid State = (1596, 256)"

To connect SASPy to the workspace server I am using IOM (which, again, works fine most of the time).

Does anybody has any pointers as to how to solve this?

 - OS: Ubuntu Linux running through WSL 2
 - SASPy Version: 4.2.0

**Comment by tomweber-sas** [comment]
Hey, glad you're able to use this for the app you've created. Sorry you're having this occasional trouble. Since the error is when trying to create a connection (based upon what you showed so far), I maybe wouldn't read too much into the other message, although, can you show me the real output itself (traceback and SASLOG if that's where you saw the no assign line), so I can really see what happened? Bit's and pieces of the full output aren't as helpful. There's usually an actual error message when the 'we failed in getConnection' happens. So the full output will help to see what the real problem is. So let's start with that. 
Thanks!
Tom

**Comment by rodrigoalatorre** [comment]
Hey, thanks for your reply, Tom. I hadn't been able to replicate the behaviour as described, until today. Actually, I am not getting much else aside from the Pid State and the "No logical assign for filename" errors.
This is the complete traceback I am getting:

```
We failed in getConnection
No logical assign for filename _TOMODS1.
We failed in getConnection
No logical assign for filename _TOMODS1.

SAS process has terminated unexpectedly. Pid State= (5076, 256)
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
INFO:werkzeug:172.17.0.1 - - [24/May/2022 13:55:40] "GET /api_route HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/dash/dash/API_CI_Flask/server.py", line 30, in query_ci
    res = query.sas_query()
  File "/var/dash/dash/API_CI_Flask/consultar.py", line 289, in sas_query
    datos_patrones = self.sas.sasdata(archivo_patrones, "home").to_df()
  File "/usr/local/lib/python3.8/site-packages/saspy/sasbase.py", line 1051, in sasdata
    if not self.exist(sd.table, sd.libref):
  File "/usr/local/lib/python3.8/site-packages/saspy/sasbase.py", line 915, in exist
    return self._io.exist(table, libref)
  File "/usr/local/lib/python3.8/site-packages/saspy/sasioiom.py", line 1160, in exist
    exists = int(l2[0])
ValueError: invalid literal for int() with base 10: 'No SAS process attached. SAS process has terminated unexpectedly.'
```

What weirds me out the most is that I am not even runnning a very complex query on the server, just a regular proc sql; with a bunch of where clauses on an indexed field. Even more daunting, if I copy and paste the code into my Enterprise Guide client and submit it, it only takes a couple of seconds to get the results. Any pointers?

**Comment by rodrigoalatorre** [comment]
Sure, Tom (thanks again), this is my configuration file:

'''
SAS_config_names=['iom_com']
iom_com = {
		      'java': "/usr/local/openjdk-17/bin/java",
                      'iomhost':'172.16.23.242',
                      'iomport': 8591,
                      'encoding':'windows-1252',
		      'appserver':'SASApp - Workspace Server',
		      'omruser' : username,
		      'omrpw' : pwd
                     }
'''

This is basically the code we're running:

'''
options nocenter;
options threads cpucount=16;
options sortsize=64G;
options SUMSIZE=64G;
proc sql; 
            create table work.patrones as
            select EMPLOYER_ID, count(distinct PERSON_ID) as tamaño_patron
            from oracle.oracle_table 
            where (EMPLOYER_ID = '19180837' or EMPLOYER_ID = 'D9231195' 
 or EMPLOYER_ID = 'Z8770294' 
) and start_date <= '24May2022:00:00:00'dt
            and end_date >= '27Aug2020:00:00:00'dt
            group by EMPLOYER_ID;
'''

**Comment by rodrigoalatorre** [comment]
Sure, Tom (thanks again), this is my configuration file:

```
SAS_config_names=['iom_com']
iom_com = {
		      'java': "/usr/local/openjdk-17/bin/java",
                      'iomhost':'server_ip_address',
                      'iomport': 8591,
                      'encoding':'windows-1252',
		      'appserver':'SASApp - Workspace Server',
		      'omruser' : username,
		      'omrpw' : pwd
                     }

```
This is basically the code we're running:
```
options nocenter;
options threads cpucount=16;
options sortsize=64G;
options SUMSIZE=64G;
proc sql; 
            create table work.patrones as
            select EMPLOYER_ID, count(distinct PERSON_ID) as tamaño_patron
            from oracle.oracle_table 
            where (EMPLOYER_ID = '19180837' or EMPLOYER_ID = 'D9231195' 
 or EMPLOYER_ID = 'Z8770294' 
) and start_date <= '24May2022:00:00:00'dt
            and end_date >= '27Aug2020:00:00:00'dt
            group by EMPLOYER_ID;

```

**Comment by tomweber-sas** [comment]
ok, thanks, I see you're using IOM (not COM; which is good). And you're not providing your own classpath (which you shouldn't). That confirms you're not using an old jar file with newer code or something strange like that which is something I've run into a couple time, a while back and can be really strange to try to diagnose. The SAS code isn't so much the thing as the SASPy code I was wondering about. Do you create a SASsession object and then use it for whatever requests your trying to submit, or do you have a long running session you try to use across multiple requests, such that it could have timed out and went away out from under your app?

**Comment by rodrigoalatorre** [comment]
I'll contact the SAS amins, ask for the logs and get back to you. Thank you a lot, Tom, I really appreciate it.

R.

**Comment by tomweber-sas** [comment]
Cool, I wish I had a better idea of what could be happening. The other thought I'm having is if you might be doing something in your app where (you said you're creating multiple connections), you may be trying to make a request on a session variable that's not a valid one anymore? Or something like that?

**Comment by tomweber-sas** [comment]
checking back in. Were you able to get any more info on this? Logs or double checking the logic in your app regarding which SASsession you were trying to use?

**Comment by tomweber-sas** [comment]
Hey, this one is pretty old and I don't have the info from the server side to know what's going on. Looking to clean up old issues, so is this still an issue, and if so, can we get object spawner logs and workspace server logs from a failure case to look at? Might need tech supports help on that side if that's not something you can easily get. 
Or did you look at the logic of your code and find anything where you might be using the wrong SASsession object for the case where it fails? That was a possibility, especially given where it was failing (from that first traceback).
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey, that's great news! I really rather prefer knowing what was going on, but we don't always get what we want :) Glad it's working now as expected! Let me know if you need anything else!
Thanks,
Tom
