### ISSUE TITLE
We failed in getConnection An exception was thrown during the encryption key exchange.

### ISSUE THREAD

**Issue by Samuelnikhade** [sassoftware/saspy#470]
I'm trying to connect SAS ODA via Windows Machine

With the help of below link, I have made changes in "sascfg_personal.py" and "_authinfo"
https://support.sas.com/ondemand/saspy.html

Below code which I'm trying to execute in Pycharm
import saspy
sas = saspy.SASsession()

below are the installation in my system
Conda Python version : 3:10
Saspy version : saspy-4.2.0
Java version : "1.8.0_333"

**Below is the error that Im getting**

C:\Users\sam\.conda\envs\sastopython\python.exe C:/Users/sam/PycharmProjects/try1sastopy/testsas2py.py
Using SAS Config named: oda
Traceback (most recent call last):
  File "C:\Users\sam\PycharmProjects\try1sastopy\testsas2py.py", line 8, in <module>
    sas = saspy.SASsession(cfgfile='C:/Users/sam/.conda/envs/try1sastopy/Lib/site-packages/saspy/sascfg_personal.py')
  File "C:\Users\sam\.conda\envs\sastopython\lib\site-packages\saspy\sasbase.py", line 599, in __init__
    raise SASIOConnectionError(res)
saspy.sasexceptions.SASIOConnectionError: Failure establishing SASsession.
 No SAS process attached. SAS process has terminated unexpectedly.
We failed in getConnection
An exception was thrown during the encryption key exchange.

SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe with the following parameters:['C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath\\java.exe', '-classpath', 'C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\saspyiom.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-1.2-api-2.12.4.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-api-2.12.4.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\log4j-core-2.12.4.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sas.security.sspi.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sas.core.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sas.svc.connection.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sas.rutil.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sas.rutil.nls.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\iomclient\\sastpj.rutil.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-internal-api.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-omgapi.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\thirdparty\\glassfish-corba-orb.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\thirdparty\\pfl-basic.jar;C:\\Users\\sam\\.conda\\envs\\sastopython\\lib\\site-packages\\saspy\\java\\thirdparty\\pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '50352', '-stdoutport', '50353', '-stderrport', '50354', '-iomhost', 'odaws01-apse1-2.oda.sas.com;odaws02-apse1-2.oda.sas.com', '-iomport', '8591', '-user', 'xyz@gmail.com', '-lrecl', '1048576', '']

No SAS process attached. SAS process has terminated unexpectedly.
Invalid response from SAS on inital submission. printing the SASLOG as diagnostic

Process finished with exit code 1

**Comment by Samuelnikhade** [comment]
Access Method         = IOM
SAS Config name       = oda
SAS Config file       = C:\Users\sam\Anaconda3\envs\sastopy\lib\site-packages\saspy\sascfg_personal.py
WORK Path             = /saswork/SAS_work6AFB0001CF1A_odaws01-apse1-2.oda.sas.com/SAS_work2ABB0001CF1A_odaws01-apse1-2.oda.sas.com/
SAS Version           = 9.04.01M6P11072018
SASPy Version         = 4.3.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf-8
SAS process Pid value = 118554

**Comment by Samuelnikhade** [comment]
Jar file worked, Thanks

**Comment by Samuelnikhade** [comment]
Jar file worked, Thanks
