### ISSUE TITLE
Error when starting IOM Session

### ISSUE THREAD

**Issue by thypad** [sassoftware/saspy#51]
I'm trying to start an IOM session with jupyter, the error I get is:

```
Unable to parse the name value "applicationname=ConnectionService%20904400".

SAS process has terminated unexpectedly. RC from wait was: 4294967290
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', 'C:\\Program Files\\SAS PC File Server\\M4\\9.4\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.svc.connection.jar;C:\\Program Files\\SAS PC File Server\\M4\\9.4\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\log4j.jar;C:\\Program Files\\SAS PC File Server\\M4\\9.4\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.security.sspi.jar;C:\\Program Files\\SAS PC File Server\\M4\\9.4\\SASDeploymentManager\\9.4\\products\\deploywiz__94470__prt__xx__sp0__1\\deploywiz\\sas.core.jar;C:\\Users\\PTHYAGO\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\saspy\\java\\saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '54329', '-stdoutport', '54330', '-stderrport', '54331', '-iomhost', 'sasprod', '-iomport', '8591', '-user', 'denoren', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
```

When I run the same command on Windows power shell, I get:
```
java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.net.PlainSocketImpl.connect(Unknown Source)
        at java.net.SocksSocketImpl.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.connect(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at java.net.Socket.<init>(Unknown Source)
        at pyiom.saspy2j.main(saspy2j.java:119)
Exception in thread "main" java.lang.NullPointerException
        at pyiom.saspy2j.main(saspy2j.java:126)
```
Any idea how to solve this?

**Comment by tomweber-sas** [comment]
Sorry, I'm on vacation through next week, but I have a minute now. Can you provide information regarding how you installed this, how you configure it, if you followed the documentation for install/config? Please read the following:
https://sassoftware.github.io/saspy

I have no idea what this is: 
```
Unable to parse the name value "applicationname=ConnectionService%20904400".
```
Can you show me your config file and provide the code you tried to run? My initial guess is something wrong in your config file.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
@thypad , I'm back in the office. Did you resolve this issue? Did you find where 
```
"applicationname=ConnectionService%20904400"
```
was specified? Was it in your sascfg.py (or sascfg_personal.py) file somewhere?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Is this still an issue, or did you get your configuration working? I'll go ahead and close this in a couple if I don't hear back. If you need to reopen, feel free.

Thanks,
Tom
